version: 2.1
orbs:
  node: circleci/node@1.1.6
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
            - run: npm run coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test